### ISSUE TITLE
Module not found "https://deno.land/std/hash/mod.ts"

### ISSUE THREAD

**Issue by waptik** [dcdunkan/deno_gramjs#16]
Hi,

I'm trying to use this module but i looks like `hash` is no longer available in the standard library.
Here's the error log
```sh
error: Module not found "https://deno.land/std/hash/mod.ts".
    at https://deno.land/x/god_crypto@v0.2.0/src/eme_oaep.ts:1:28

```

**Comment by rojvv** [comment]
I’m not able to reproduce this. Could you describe your situation in advance?

**Comment by rojvv** [comment]
Good. I reproduced it with the `--reload` parameter.

**Comment by rojvv** [comment]
@waptik You can play with https://raw.githubusercontent.com/roj1512/grm/16-workaround/mod.ts until @dcdunkan finds time to merge #17.

**Comment by waptik** [comment]
Thanks for the suggestion but i already have a workaround https://github.com/waptik/grm/blob/main/deps.ts#L28

**Comment by waptik** [comment]
@roj1512 Can you please check https://t.me/xorchat/969 and see why i am not receiving any response locally?
