### ISSUE TITLE
Deno Deploy: Dynamic import is not enabled in this context.

### ISSUE THREAD

**Issue by waptik** [dcdunkan/deno_gramjs#36]
As i was planning on deploying my bot on https://dash.deno.com, i got the following error in the logs that crashed the server

![image](https://user-images.githubusercontent.com/1687551/213619297-dcfef99a-1fbb-47f8-8b23-0894448c3474.png)

**Comment by rojvv** [comment]
The issue is clear, Deno Deploy does not support dynamic imports. Plus, Grm can’t run on serverless architectures.

**Comment by roj1512** [comment]
Neither Deno Deploy supports the Deno APIs that Grm requires in order to function.

**Comment by waptik** [comment]
I see. Thanks for letting me know.
